{% set name = "latex-rubber" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d52b6f928022efd928d85da6c5cad89c8b42f9f413ca64d5f385484e788f9a7f

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - rubber
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/latex-rubber/rubber
  summary: an automated system for building LaTeX documents
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - HaoZeke
